import Pricing from "./Pricing";
import tick from "../asset/Group 221.svg";
export default {
  title: "Pricing",
  component: Pricing,
  argTypes: {
    storage: { control: "text" },
    writings: { control: "text" },
    button: { control: "text" },
    amount: { control: "text" },
    gb: { control: "text" },
    button2: { control: "text" },
    amount2: { control: "text" },
    gb2: { control: "text" },
    bigButton: { control: "text" },
    tick: { control: "text" },
    specs: { control: "text" },
    padding: { control: "text" },
    width: { control: "number" },
    height: { control: "number" },
    display: { control: "text" },
    justifyContent: { control: "text" },
    alignItems: { control: "text" },
    boxShadow: { control: "text" },
    backgroundColor: { control: "color" },
    headWeight: { control: "text" },
    headSize: { control: "number" },
    headColor: { control: "color" },
    hrTextDecoration: { control: "text" },
    hrWidth: { control: "number" },
    hrColor: { control: "color" },
    writingColor: { control: "color" },
    writingSize: { control: "number" },
    writingWidth: { control: "number" },
    amountAlign: { control: "text" },
    amountColor: { control: "color" },
    amountDirection: { control: "text" },
    amountDisplay: { control: "text" },
    amountJustify: { control: "text" },
    amountSize: { control: "number" },
    amountWeight: { control: "text" },
    gbFontSize: { control: "number" },
    gbWeight: { control: "text" },
    specContents: { control: "text" },
    specDisplay: { control: "text" },
    specGap: { control: "text" },
    specItems: { control: "text" },
    borderRadius: { control: "text" },
    flexDirection: { control: "text" },
    textAlign: { control: "text" },
    hrBorderW: { control: "number" },
    gap: { control: "number" },
    amountAlign2: { control: "text" },
    amountDirection2: { control: "text" },
    amountDisplay2: { control: "text" },
    amountJustify2: { control: "text" },
  },
};

export const Price = (args) => <Pricing {...args} />;
Price.args = {
  storage: "Storage",
  writings:
    "Access a complete decentralized storage with simple, pay-as-you-go pricing",
  amount: "$0.008",
  gb: "per GB/month",
  specs: "Everything you need to storage & share files",
  tick: tick,
  width: "563px",
  height: "574px",
  display: "flex",
  flexDirection: "column",
  alignItems: "center",
  justifyContent: "center",
  boxShadow: "0px 4px 24px 0px rgba(0,0,0,0.02)",
  borderRadius: "24px",
  hrWidth: "30px",
  hrTextDecoration: "dashed",
  hrBorderW: "1px",
  textAlign: "center",
  amountDisplay: "flex",
  amountDirection: "column",
  amountAlign: "center",
  amountSize: "64px",
  amountWeight: "600",
  amountColor: "rgb(11,13,14)",
  specDisplay: "flex",
  specGap: "16px",
  specItems: "center",
  amountDisplay2: "none",
  gap: "2rem",
  writingWidth: "330px",
  backgroundColor: "rgb(255, 255, 255)",
  headSize: "32px",
};
